# Generated by Django 3.1.3 on 2020-12-15 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_delete_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='password',
            new_name='password_main',
        ),
    ]
