# Generated by Django 3.1.3 on 2020-12-15 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20201215_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password_main',
        ),
    ]
